### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by brendanfh** [onyx-lang/onyx#135]
- [ ] Support [WASM Object Files](https://github.com/WebAssembly/tool-conventions/blob/main/Linking.md)
    - [ ] Change memory layout to match other compilers #133
    - [ ] Support linking an object file into a compilation
    - [ ] Support outputting a linkable WASM file

- [ ] Support the WASM Component Model
    - [ ] Support outputting "components"
    - [ ] Library to generate bindings from WIT definitions

- [ ] WebAssembly Extensions
    - [ ] Reference types support through a new builtin type
    - [ ] Wasm GC primitives?

**Comment by Qodestackr** [comment]
Is this lang in constant development?

**Comment by brendanfh** [comment]
In short, yes, this language is still in a relatively early phase of its life where new features are being added and some breaking changes are happening.

The language syntax and semantics are nearing a point where I would call them complete, as I don't intend to add too many more features there. Places where the language can be used are still in active development, hence the items listed on the small roadmap above.

I desperately need to spend time to update this roadmap because it is missing many things that need to be done for Onyx.

**Comment by Qodestackr** [comment]
I will see how I can be helpful. Not really a compiler designer but can bring my skills in docs translation, Playing around with features and seeing how we can push wasm
